---
- name: Include SystemD role tasks ...
  ansible.builtin.include_tasks: "{{ outer_item }}"
  loop:
    - user.yml
    - system.yml
  loop_control: # avoids 'item' variable overwriting in inner tasks
    loop_var: outer_item
  when: run_systemd_role
