- name: Create systemd user directories
  ansible.builtin.file:
    path: "{{ common_user.home }}/{{ item.dest_dir }}"
    state: directory
  loop: "{{ systemd_user.templates }}"

- name: Create systemd user directories
  ansible.builtin.file:
    path: "{{ common_user.home }}/{{ item.dest_dir }}"
    state: directory
  loop: "{{ systemd_user.files }}"

- name: Copy systemd template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ common_user.home }}/{{ item.dest_dir }}/{{ item.dest_file }}"
  loop: "{{ systemd_user.templates }}"

- name: Copy systemd files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ common_user.home }}/{{ item.dest_dir }}/{{ item.dest_file }}"
  loop: "{{ systemd_user.files }}"

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Enable Syncthing service
  ansible.builtin.systemd:
    name: syncthing
    state: started
    enabled: true
    scope: user
  when: systemd_user.quadlets.syncthing.enable

- name: Enable podman podman-auto-update.timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    enabled: true
    scope: user

# To allow for systemd services to be started at boot without login (and continue running after logout) of the individual users, you need to enable lingering. You can do that via loginctl enable-linger <username>. It is buried in the manpages of podman-generate-systemd:
# http://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html

- name: "Check if lingering is enabled for user {{ common_user.name }}"
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ common_user.name }}"
  register: linger
  changed_when: false
  when: systemd_user.linger.enable

- name: "Enable lingering for user {{ common_user.name }}"
  ansible.builtin.command: "loginctl enable-linger {{ common_user.name }}"
  when:
  - not linger.stat.exists
  - systemd_user.linger.enable
