---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop: "{{ filesystem_folders }}"
  become: true

- name: Configure mounts
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
    dump: "{{ item.dump }}"
    passno: "{{ item.passno }}"
  loop: "{{ filesystem_mounts }}"
  become: true

- name: Create required symlinks
  ansible.builtin.file:
    src: "{{ item.link_src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ filesystem_symlinks }}"
  become: true
