ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-latest}"
FROM quay.io/fedora/fedora:${FEDORA_MAJOR_VERSION} AS builder

WORKDIR /tmp

RUN touch /.dockerenv \
    && dnf install -y xz --setopt=install_weak_deps=False \
    && useradd nix && mkdir -m 0755 /nix && chown nix /nix

USER nix
RUN curl -fLs https://nixos.org/nix/install | sh -s -- --no-daemon --yes

USER root
RUN cp -pr /home/nix/.local/state/nix/profiles/profile-1-link /nix/var/nix/profiles/default

FROM ghcr.io/aorith/blueconfig:stable

COPY --from=builder --chown=1000:1000 /nix /usr/share/nix

RUN systemctl enable nix.mount \
    && rpm-ostree cleanup --repomd \
    && ostree container commit

# vim:ft=dockerfile
