- hosts: all

  pre_tasks:
    - name: Load variables for {{ ansible_hostname }}
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/configs/{{ ansible_hostname }}.yml"

  roles:
    - { role: filesystem, when: ansible_os_family != "NixOS" }
  # - { role: ostree, when: ansible_os_family != "NixOS" }
    - { role: flatpak }
    - { role: systemd, when: ansible_os_family != "NixOS" }
