# Common
# --------------------------------------------------
common_hostname: trantor

common_user:
  name: 'aorith'
  home: '/var/home/aorith'
  uid: 1000
  gid: 1000

# Filesystem role
# --------------------------------------------------
run_filesystem_role: true

filesystem_folders:
- {path: "/mnt/storage", owner: 'root', group: 'root', mode: '0775'}
- {path: "/mnt/storage/disk1", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775'}
- {path: "/mnt/storage/disk2", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775'}
- {path: "/mnt/storage/tank", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775'}

# dump: (backups) see 'man dump 8'
# passno: see 'man fsck 8' it's the order for fsck, usually root is 0 and the rest is 2
filesystem_mounts:
- {src: "LABEL=TANK", path: "/mnt/storage/tank", fstype: "btrfs", opts: "defaults,compress=zstd:1", state: "mounted", dump: '0', passno: '0'}
- {src: "LABEL=DISK1", path: "/mnt/storage/disk1", fstype: "ext4", opts: "defaults,noatime", state: "mounted", dump: '0', passno: '2'}
- {src: "LABEL=DISK2", path: "/mnt/storage/disk2", fstype: "ext4", opts: "defaults,noatime", state: "mounted", dump: '0', passno: '2'}

filesystem_symlinks:
- {link_src: "/mnt/storage", dest: "/var/home/aorith/storage"}
- {link_src: "/mnt/storage/tank/data/syncthing", dest: "/var/home/aorith/Syncthing"}
- {link_src: "/mnt/storage/tank/work-in-progress", dest: "/var/home/aorith/work-in-progress"}

# Systemd role
# --------------------------------------------------
run_systemd_role: true

systemd_user:
  files:
  - {src: "syncthing.container", dest_dir: ".config/containers/systemd", dest_file: "syncthing.container"}
  templates:
  - {src: "user/containers/syncthing.{{ common_hostname }}.env.j2", dest_dir: ".config/containers/systemd", dest_file: "syncthing.env"}
  linger:
    enable: true
  quadlets:
    syncthing:
      enable: true

systemd_system:
  wake_on_lan:
  - {name: "enp8s0", macaddr: "a8:5e:45:b3:10:95",}

systemd_disable_sleep:
  enable: true

# vim:ft=yaml.ansible:
