# Common
# --------------------------------------------------
common_user:
  name: 'aorith'
  home: '/var/home/aorith'
  uid: 1000
  gid: 1000

# Filesystem role
# --------------------------------------------------
run_filesystem_role: yes

filesystem_folders:
  - { path: "/var/home/aorith/storage",       owner: 'root',                   group: 'root',                   mode: '0775' }
  - { path: "/var/home/aorith/storage/disk1", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775' }
  - { path: "/var/home/aorith/storage/disk2", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775' }
  - { path: "/var/home/aorith/storage/tank",  owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775' }

# dump: (backups) see 'man dump 8'
# passno: see 'man fsck 8' it's the order for fsck, usually root is 0 and the rest is 2
filesystem_mounts:
  - { src: "LABEL=tank",  path: "/var/home/aorith/storage/tank",  fstype: "btrfs", opts: "defaults,compress=zstd:1", state: "mounted", dump: '0', passno: '0' }
  - { src: "LABEL=DISK1", path: "/var/home/aorith/storage/disk1", fstype: "ext4",  opts: "defaults,noatime",         state: "mounted", dump: '0', passno: '2' }
  - { src: "LABEL=DISK2", path: "/var/home/aorith/storage/disk2", fstype: "ext4",  opts: "defaults,noatime",         state: "mounted", dump: '0', passno: '2' }

filesystem_symlinks:
  - { link_src: "/var/home/aorith/storage/tank/data/syncthing", dest: "/var/home/aorith/Syncthing" }

# Flatpak role
# --------------------------------------------------
run_flatpak_role: yes

# flatpak remotes --show-details
flatpak_remotes:
  - { name: 'flathub', url: 'https://dl.flathub.org/repo/flathub.flatpakrepo' }

flatpak_packages:
  - { remote: 'flathub', package: 'chat.rocket.RocketChat' }
  - { remote: 'flathub', package: 'com.bitwarden.desktop' }
  - { remote: 'flathub', package: 'com.calibre_ebook.calibre' }
  - { remote: 'flathub', package: 'com.github.tchx84.Flatseal' } # manage flatpak permissions
  - { remote: 'flathub', package: 'com.google.Chrome' }
  - { remote: 'flathub', package: 'com.mattjakeman.ExtensionManager' }
  - { remote: 'flathub', package: 'com.obsproject.Studio' }
  - { remote: 'flathub', package: 'com.spotify.Client' }
  - { remote: 'flathub', package: 'com.valvesoftware.Steam' }
  - { remote: 'flathub', package: 'com.vscodium.codium' }
  - { remote: 'flathub', package: 'io.mpv.Mpv' }
  - { remote: 'flathub', package: 'net.cozic.joplin_desktop' }
  - { remote: 'flathub', package: 'org.blender.Blender' }
  - { remote: 'flathub', package: 'org.flameshot.Flameshot' }
  - { remote: 'flathub', package: 'org.gimp.GIMP' }
  - { remote: 'flathub', package: 'org.gnome.Firmware' }
  - { remote: 'flathub', package: 'org.inkscape.Inkscape' }
  - { remote: 'flathub', package: 'org.libreoffice.LibreOffice' }
  - { remote: 'flathub', package: 'org.remmina.Remmina' }
  - { remote: 'flathub', package: 'org.videolan.VLC' }


# Systemd role
# --------------------------------------------------
run_systemd_role: yes

systemd_user:
  syncthing:
    enable: yes
  templates:
    - { src: "user/units/syncthing.trantor.service.j2", dest: "syncthing.service" }
  linger:
    enable: yes

systemd_system:
  wake_on_lan:
    - { name: "enp8s0", macaddr: "a8:5e:45:b3:10:95" }

