# Common
# --------------------------------------------------
common_hostname: trantor

common_user:
  name: 'aorith'
  home: '/var/home/aorith'
  uid: 1000
  gid: 1000

# Filesystem role
# --------------------------------------------------
run_filesystem_role: true

filesystem_folders: []

# dump: (backups) see 'man dump 8'
# passno: see 'man fsck 8' it's the order for fsck, usually root is 0 and the rest is 2
ilesystem_mounts: []

filesystem_symlinks: []

# Systemd role
# --------------------------------------------------
run_systemd_role: false

systemd_user:
  files: []
    #- {src: "syncthing.container", dest_dir: ".config/containers/systemd", dest_file: "syncthing.container"}
  templates:
    #- {src: "user/containers/syncthing.{{ common_hostname }}.env.j2", dest_dir: ".config/containers/systemd", dest_file: "syncthing.env"}
  linger: []
    enable: true

systemd_system:
  wake_on_lan: []

systemd_disable_sleep:
  enable: false

# vim:ft=yaml.ansible:
