# Common
# --------------------------------------------------
common_user:
  name: 'aorith'
  home: '/var/home/aorith'
  uid: 1000
  gid: 1000

# Filesystem role
# --------------------------------------------------
run_filesystem_role: yes

filesystem_folders:
  - { path: "/var/home/aorith/storage",       owner: 'root',                   group: 'root',                   mode: '0775' }
  - { path: "/var/home/aorith/storage/disk1", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775' }
  - { path: "/var/home/aorith/storage/disk2", owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775' }
  - { path: "/var/home/aorith/storage/tank",  owner: "{{ common_user.name }}", group: "{{ common_user.name }}", mode: '0775' }

# dump: (backups) see 'man dump 8'
# passno: see 'man fsck 8' it's the order for fsck, usually root is 0 and the rest is 2
filesystem_mounts:
  - { src: "LABEL=tank",  path: "/var/home/aorith/storage/tank",  fstype: "btrfs", opts: "defaults,compress=zstd:1", state: "mounted", dump: '0', passno: '0' }
  - { src: "LABEL=DISK1", path: "/var/home/aorith/storage/disk1", fstype: "ext4",  opts: "defaults,noatime",         state: "mounted", dump: '0', passno: '2' }
  - { src: "LABEL=DISK2", path: "/var/home/aorith/storage/disk2", fstype: "ext4",  opts: "defaults,noatime",         state: "mounted", dump: '0', passno: '2' }

filesystem_symlinks:
  - { link_src: "/var/home/aorith/storage/tank/data/syncthing", dest: "/var/home/aorith/Syncthing" }

# OsTree role
# --------------------------------------------------
run_ostree_role: yes

layered_packages:
  - alacritty.x86_64
  - cloud-utils
  - cockpit-machines
  - cockpit-navigator
  - cockpit-networkmanager
  - cockpit-ostree
  - cockpit-podman
  - cockpit-selinux
  - cockpit-storaged
  - cockpit-system
  - cockpit-ws
  - distrobox
  - genisoimage
  - gnome-tweaks
  - htop
  - net-tools
  - podman-compose # consider checking out 'podman generate kube' and 'podman play kube'
  - python3-psutil
  - vim
  - virt-install
  - virt-manager
  - virt-viewer

#base_package_remove:
#  - firefox


# Flatpak role
# --------------------------------------------------
run_flatpak_role: yes

# flatpak remotes --show-details
flatpak_remotes:
  - { name: 'flathub', url: 'https://dl.flathub.org/repo/flathub.flatpakrepo' }
  - { name: 'fedora',  url: 'oci+https://registry.fedoraproject.org' }

flatpak_packages:
  - { remote: 'flathub', package: 'com.bitwarden.desktop' }
  - { remote: 'flathub', package: 'com.calibre_ebook.calibre' }
  - { remote: 'flathub', package: 'com.github.tchx84.Flatseal' } # manage flatpak permissions
  - { remote: 'flathub', package: 'com.google.Chrome' }
  - { remote: 'flathub', package: 'com.obsproject.Studio' }
  - { remote: 'flathub', package: 'com.spotify.Client' }
  - { remote: 'flathub', package: 'com.vscodium.codium' }
  - { remote: 'flathub', package: 'io.mpv.Mpv' }
  - { remote: 'flathub', package: 'md.obsidian.Obsidian' }
  - { remote: 'flathub', package: 'net.cozic.joplin_desktop' }
  - { remote: 'flathub', package: 'org.flameshot.Flameshot' }
  - { remote: 'flathub', package: 'org.gimp.GIMP' }
  - { remote: 'flathub', package: 'org.gnome.Firmware' }
  - { remote: 'flathub', package: 'org.remmina.Remmina' }
  - { remote: 'flathub', package: 'org.videolan.VLC' }


# Systemd role
# --------------------------------------------------
run_systemd_role: yes

systemd_user:
  syncthing:
    enable: yes
  linger:
    enable: yes
  templates:
    - { src: "units/user/syncthing.trantor.service.j2", dest: "syncthing.service" }

systemd_system:
  wake_on_lan:
    - { name: "enp8s0", macaddr: "a8:5e:45:b3:10:95" }

